{
  imports = [
    ./gh.nix
    ./dotfiles.nix
    ./codex.nix
    ./niri.nix
    ./umbriel.nix
    ./themes.nix
    ./noctalia.nix
    ./alacritty.nix
    ./chromium.nix
    ./lazygit.nix
    ./zathura.nix
    ./vicinae.nix
    ./mcp.nix
    ./opencode-config.nix
    ./pi-config.nix
  ];
}
